version = 0.1
[default.deploy.parameters]
stack_name = "spring-private-mysql"
resolve_s3 = true
s3_prefix = "spring-private-mysql"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true